exports.features = [
  'popular',
  'highest_rated',
  'upcoming',
  'editors',
  'fresh_today',
  'fresh_yesterday',
  'fresh_week',
]

exports.categories = [
  'Uncategorized',
  'Abstract',
  'Aerial',
  'Animals',
  'Black and White',
  'Celebrities',
  'City and Architecture',
  'Commercial',
  'Concert',
  'Family',
  'Fashion',
  'Film',
  'Fine Art',
  'Food',
  'Journalism',
  'Landscapes',
  'Macro',
  'Nature',
  'Night',
  'Nude',
  'People',
  'Performing Arts',
  'Sport',
  'Still Life',
  'Street',
  'Transportation',
  'Travel',
  'Underwater',
  'Urban Exploration',
  'Wedding',
]
